config:
  log: console
  #log: syslog
  #log: file
  logfile: log

hosts:
  - address: 8.8.8.8
    prot: "icmp"
  - address: google.com
    prot: icmp
  - address: google.com
    prot: httpstatus
    httpstatus: 200
  - address: 52.215.222.98
    prot: httpstring
    httpstring: Glasswall
  - address: 54.77.168.168
    prot: icap
    icaptestfile: a.pdf
    icaptimeout: 10